apiVersion: apps/v1
kind: Deployment

metadata:
  name: todos-backend
  labels:
    tier: server

spec:
  replicas: 2
  selector:
    matchLabels:
      tier: server
  template:
    metadata:
      #name: todos-backend
      labels:
        tier: server
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z todos-db 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
        - name: todos-backend-container
          image: aparihar/todosserver:latest
          ports:
            - containerPort: 4000
          env:
            - name: RDS_HOST
              valueFrom:
                secretKeyRef:
                  name: todos-mysql-connection-secret
                  key: RDS_HOST
            - name: RDS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: todos-mysql-connection-secret
                  key: RDS_USERNAME
            - name : RDS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todos-mysql-connection-secret
                  key: RDS_PASSWORD
            - name: RDS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: todos-mysql-connection-secret
                  key: RDS_DB_NAME
            - name: RDS_PORT
              valueFrom:
                secretKeyRef:
                  name: todos-mysql-connection-secret
                  key: RDS_PORT

