apiVersion: v1
kind: Service

metadata:
  name: todos-backend
  labels:
    tier: backendSvc

spec:
  #type: : ClusterIP
  ports:
    - port: 8081
      targetPort: 4000

  selector:
    tier: server
