apiVersion: v1
kind: Service

metadata:
  name: todos-db
  labels:
    tier: dbSvc
  namespace: dev

spec:
  type: ClusterIP
  ports:
    - port: 3306
      #targetPort: 3306
  selector:
    tier: db
  #clusterIP: None
