apiVersion: v1
kind: Service

metadata:
  name: todos-frontend
  labels:
    tier: frontendSvc
  namespace: dev

spec:
  #type: NodePort
  ports:
    - port: 3000
      #nodePort: 30001
  selector:
    tier: client
