
apiVersion: v1
kind: Service
metadata:
  name: todos-db
  labels:
    app: todos
spec:
  #clusterIP: None
  ports:
    - port: 3306
  selector:
    app: todos
    tier: mysqldb

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todos-db
  labels:
    app: todos
    tier: mysqldb
spec:
  serviceName: todos-db
  replicas: 2
  selector:
    matchLabels:
      app: todos
      tier: mysqldb
  template:
    metadata:
      labels:
        app: todos
        tier: mysqldb
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - image: aparihar/todosdb:latest
        name: mysql-container
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todos-mysql-connection-secret
                key: RDS_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: todos-mysql-connection-secret
                key: RDS_DB_NAME
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: todos-mysql-connection-secret
                key: RDS_USERNAME
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todos-mysql-connection-secret
                key: RDS_PASSWORD
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: todos-mysql-connection-secret
                key: RDS_HOST
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: todos-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: todos-persistent-storage
        persistentVolumeClaim:
          claimName: todos-pvc




