# What is being claimed?
# It is a request for storage by a user that can be fulfilled by a PV
# in the below pvc, we are claiming a local-storage which is implemented as hostPath
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todos-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: standard
  #storageClassName: local-storage

---
# How is the physical storage implemented
# PV is a cluster resource, manually provisioned by the cluster admin
apiVersion: v1
kind: PersistentVolume
metadata:
  name: todos-host-pv
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    type: DirectoryOrCreate
    path: /mnt/host/local/store

---
# https://kubernetes.io/docs/concepts/storage/storage-classes
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: todos-aws-ebs
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2 # default, general purpose SSD drive
volumeBindingMode: WaitForFirstConsumer

