apiVersion: v1
kind: ConfigMap
metadata:
  name: todos-ngnix-api-gateway-config

data:
  default.conf: |
    server {
      listen 3000;

      # proxy requests based on routes
      location /api {
        proxy_pass http://todos-backend:8081;
        proxy_set_header X-Forwarded-For $remote_addr;
      }
      location / {
          root /usr/share/nginx/html;
          index index.html index.htm;
      }
    }